apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: laravel-app
type: Opaque
data:
  # App Configuration
  APP_NAME: SW52ZXN0aWZ5
  APP_ENV: cHJvZHVjdGlvbg==
  APP_KEY: YmFzZTY0OmdqTHQ0cGRPM1Uwd3RVbVRXTGZRb2w1RmZuczR1eEcxSUNuN3lFa0d0QzQ9
  APP_DEBUG: ZmFsc2U=
  APP_URL: aHR0cDovL2xvY2FsaG9zdA==

  DATABASE_URL: cHNxbCAncG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfWHBmMVpvMFVDYVRWQGVwLWNyaW1zb24tcmVzb25hbmNlLWE5a2V5dTR5LXBvb2xlci5nd2MuYXp1cmUubmVvbi50ZWNoL25lb25kYj9zc2xtb2RlPXJlcXVpcmUmY2hhbm5lbF9iaW5kaW5nPXJlcXVpcmUn

  # Logging
  LOG_CHANNEL: c3RhY2s=
  LOG_DEPRECATIONS_CHANNEL: bnVsbA==
  LOG_LEVEL: ZGVidWc=

  # Drivers
  BROADCAST_DRIVER: bG9n
  CACHE_DRIVER: ZmlsZQ==
  FILESYSTEM_DISK: bG9jYWw=
  QUEUE_CONNECTION: c3luYw==
  SESSION_DRIVER: ZmlsZQ==
  SESSION_LIFETIME: MTIw

  # Memcached
  MEMCACHED_HOST: MTI3LjAuMC4x

  # Redis
  REDIS_HOST: MTI3LjAuMC4x
  REDIS_PASSWORD: bnVsbA==
  REDIS_PORT: NjM3OQ==

  # Pusher (empty values except for cluster)
  PUSHER_PORT: NDQz
  PUSHER_SCHEME: aHR0cHM=
  PUSHER_APP_CLUSTER: bXQx

  # Vite Pusher (will use the same as above)
  VITE_PUSHER_PORT: NDQz
  VITE_PUSHER_SCHEME: aHR0cHM=
  VITE_PUSHER_APP_CLUSTER: bXQx

  # Mail Configuration
  MAIL_MAILER: c210cA==
  MAIL_HOST: c210cC5nbWFpbC5jb20=
  MAIL_PORT: NTg3
  MAIL_USERNAME: c2FuZ2tpcGtvZWNoQGdtYWlsLmNvbQ==
  MAIL_PASSWORD: dGNyeHNrem1nZ2pjdmd6YQ==
  MAIL_ENCRYPTION: dGxz
  MAIL_FROM_ADDRESS: c2FuZ2tpcGtvZWNoQGdtYWlsLmNvbQ==
  MAIL_FROM_NAME: SW52ZXN0aWZ5

  # Grafana
  GRAFANA_USER: YWRtaW4=
  GRAFANA_PASSWORD: engwMDEx
