replicaCount: 1

image:
  repository: ektowett/investify-php-fpm
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: true

# livenessProbe:
#   exec:
#     command: ["php-fpm-healthcheck"]
#   initialDelaySeconds: 5
#   periodSeconds: 10
#   timeoutSeconds: 5
#   failureThreshold: 3

# readinessProbe:
#   exec:
#     command: ["php-fpm-healthcheck"]
#   initialDelaySeconds: 3
#   periodSeconds: 10
#   timeoutSeconds: 5
#   failureThreshold: 3

containerPort: 9000

service:
  type: ClusterIP
  port: 9000

resources:
  limits:
    cpu: 400m
    memory: 448Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

pdb:
  enabled: false
  minAvailable: 1

externalSecrets:
  - name: investify-app-secrets
    refreshInterval: 5m
    secretStoreRefName: vault-backend
    targetName: investify-app-secrets
    dataKey: prod/investify-app-secrets

env:
  APP_NAME: Investify
  APP_ENV: prod
  APP_DEBUG: false
  APP_URL: https://investify.citizix.com
  LOG_CHANNEL: stack
  LOG_DEPRECATIONS_CHANNEL: null
  LOG_LEVEL: debug
  # DB_CONNECTION: mysql
  # DB_HOST: 127.0.0.1
  # DB_PORT: 3306
  # DB_DATABASE: investify
  # DB_USERNAME: dev
  # DB_PASSWORD: zx0011
  DB_CONNECTION: pgsql
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  FILESYSTEM_DISK: local
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"
  MEMCACHED_HOST: 127.0.0.1
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET:
  AWS_USE_PATH_STYLE_ENDPOINT: false
  PUSHER_APP_ID:
  PUSHER_APP_KEY:
  PUSHER_APP_SECRET:
  PUSHER_HOST:
  PUSHER_PORT: 443
  PUSHER_SCHEME: https
  PUSHER_APP_CLUSTER: mt1
  VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  VITE_PUSHER_HOST: "${PUSHER_HOST}"
  VITE_PUSHER_PORT: "${PUSHER_PORT}"
  VITE_PUSHER_SCHEME: "${PUSHER_SCHEME}"
  VITE_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
  MAIL_MAILER: smtp
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: 587
  MAIL_ENCRYPTION: tls
  MAIL_FROM_NAME: "${APP_NAME}"

secretEnv:
  APP_KEY:
    name: investify-app-secrets
    key: app-key
  DB_HOST:
    name: investify-app-secrets
    key: db-host
  DB_PORT:
    name: investify-app-secrets
    key: db-port
  DB_DATABASE:
    name: investify-app-secrets
    key: db-name
  DB_USERNAME:
    name: investify-app-secrets
    key: db-user
  DB_PASSWORD:
    name: investify-app-secrets
    key: db-password
  REDIS_HOST:
    name: investify-app-secrets
    key: redis-host
  REDIS_PASSWORD:
    name: investify-app-secrets
    key: redis-password
  REDIS_PORT:
    name: investify-app-secrets
    key: redis-port
  MAIL_USERNAME:
    name: investify-app-secrets
    key: mail-username
  MAIL_PASSWORD:
    name: investify-app-secrets
    key: mail-password
  MAIL_FROM_ADDRESS:
    name: investify-app-secrets
    key: mail-from-address
